# SPDX-FileCopyrightText: 2022-2023 Gilles Caulier <caulier dot gilles at gmail dot com>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/blocks/workflow.yml
variables:
    EPUB_NAME: LabplotManual
    DOC_ROOT: source/
    WEBSITE_LANGUAGES: en ca cs de es fi fr it lt nl pt_PT sk uk_UA zh_CH

# Replace build_sphinx_app_docs by the kde template once
# https://github.com/sphinx-doc/sphinx/issues/13177 is fixed
# Commit of MR https://invent.kde.org/documentation/docs-labplot-org/-/merge_requests/4 can be reverted
# /gitlab-templates/website-sphinx-app-docs.yml
build_sphinx_app_docs:
  image: invent-registry.kde.org/sysadmin/ci-images/staticweb:latest
  tags:
    - Linux
  stage: build
  variables:
    GIT_DEPTH: "3"
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git
    - git clone https://invent.kde.org/sysadmin/ci-notary-service.git
    - git clone --branch master --single-branch --depth 1 https://invent.kde.org/education/labplot.git # clone labplot repo to extract sdk docs
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - doxygen # generate doxygen xml docs for breathe to consume
    - |
      langList=$WEBSITE_LANGUAGES
      if [ $CI_COMMIT_REF_PROTECTED != "true" ]; then
        langList=en
      fi
    - |
      for langToBuild in $langList; do
        # build html
        sphinx-build -M html "$DOC_ROOT" _staging/$langToBuild -D language="$langToBuild" -w _logs/warnings-$langToBuild-html.log -j auto
        mkdir -p public/$langToBuild/
        mv _staging/$langToBuild/html/* public/$langToBuild/
        # build epub
        #sphinx-build -M epub "$DOC_ROOT" _staging/$langToBuild -D language="$langToBuild" -w _logs/warnings-$langToBuild-epub.log -j auto
        #mkdir public/$langToBuild/epub/
        #mv _staging/$langToBuild/epub/*.epub public/$langToBuild/epub/
      done
    # turn duplicated files like image for each language into symlinks to reduce file size
    - rdfind -makesymlinks true -makeresultsfile true $CI_PROJECT_DIR/public/
    - mv results.txt _logs/rdfind-log.txt
    # make symlinks relative (rdfind creates absolute symlinks)
    - symlinks -cr $CI_PROJECT_DIR/public/ | tee _logs/symlinks-log.txt
    # Publish
    - python3 -u ci-notary-service/publishwebsite.py --config ci-utilities/signing/publishwebsite.ini public/
    # Cleanup ebup files for artifacts capturing as they are too big
    - rm -f public/*/epub/*.epub
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - _logs/
      - public/
      - task*.log
    exclude:
      - public/**/*.epub # Do not capture the epubs, they are too big in most cases


run_tests:
  stage: validate
  image: invent-registry.kde.org/sysadmin/ci-images/staticweb:latest
  tags:
    - Linux
  script:
    # Run unit-tests
    - make test
    # ignore result of linkcheck because it raises an error but when fixing the error
    # The resulting links in the final html do not work anymore
    # Introduced with c0bb0f84cb8b5f73a9df90bf832572208572e4e8
    # https://github.com/sphinx-doc/sphinx/issues/9383
    - make linkcheck || true

